#!/usr/bin/env bash
ln -sf MIPS/{*.ml{,i},libmincaml.S} .
cd test; ln -sf MIPS/{,too}manyargs.ml .; cd ..
cd shootout; ln -sf MIPS/Makefile .; cd ..
cd bytemark; ln -sf MIPS/Makefile .; cd ..
cd min-rt; ln -sf MIPS/globals.s .; cd ..
