print_int (int_of_float 3.7);
print_int (int_of_float 3.5);
print_int (int_of_float 3.2);
print_int (int_of_float 3.0);
print_int (int_of_float 0.0);
print_int (int_of_float (-0.0));
print_int (int_of_float (-3.0));
print_int (int_of_float (-3.2));
print_int (int_of_float (-3.5));
print_int (int_of_float (-3.7))
